### ISSUE TITLE
Numbers below the last ticked number should be disabled. 

### ISSUE THREAD

**Issue by kawrou** [kashida2021/qwixx_game#35]
Once a number has been successfully marked, all the numbers below that number should be disabled. 
Numbers that were already marked and numbers that are disabled because of the rules should look visually different.

**Comment by kashida2021** [comment]
Added variables to track the highest and lowest marked numbers. Based on the row index - it will calculate the highest and lowest number marked on each coloured rows and will update the classAttributes to include a disabled class for numbers above the highest or numbers below the lowest marked choice. CSS will then apply styling to disable the button for those numbers and make them visually different
