### ISSUE TITLE
no. of numbers a player can mark

### ISSUE THREAD

**Issue by kawrou** [kashida2021/qwixx_game#40]
Currently there's no limit to how many numbers a player can mark on a given turn. 
As a "hasSubmittedChoice" property has been implemented in the Player class, we could use that to make sure a player can't mark another number. However, bare in mind that the active player can mark two numbers in one turn. 

- [x] Check if Player's hasSubmittedChoice property is false before marking a number. 
- [x] If active player, then they can mark two numbers. Maybe need to implement another flag inside of Qwixx logic to track state of no. of numbers marked by active player.

**Comment by kashida2021** [comment]
Currently I think you can only submit one choice per turn. The hasChoiceSubmitted will only reset at the end of the turn so you shouldnt be able to submit multiple choices I believe. However we do need to implement logic for the activePlayer who will have the ability to make two choices.

**Comment by kawrou** [comment]
I think can make multiple moves per turn because the makeMove method doesn't check if a player has submitted.
